title: Decoherence as First Principle
description: Exploring decoherence as a first principle in physics, with applications to quantum foundations, cosmology, and the emergence of classical reality.

url: "https://robertevanshine.com"
baseurl: ""

theme: minima

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

author:
  name: Robert Evanshine
  github: revanshine
