title: Decoherence as First Principle
description: Exploring decoherence as a first principle in physics, with applications to quantum foundations, cosmology, and the emergence of classical reality.

url: "https://robertevanshine.com"
baseurl: ""

# Disable theme to use custom book layout
# remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

author:
  name: Robert Evanshine
  github: revanshine

# Footer content
footer_content: 'Copyright &copy; 2025 Robert Evanshine. Repository code distributed under MIT license.'

# Exclude build artifacts
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - build/
  - "*.pdf"
  - "*.tex"
