name: Deploy Branch to Subdomain

on:
  push:
    branches-ignore:
      - main
  delete:

jobs:
  deploy-branch:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
          
      - name: Build Jekyll site
        run: |
          bundle exec jekyll build --baseurl "/${GITHUB_REF_NAME}"
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          destination_dir: ${{ github.ref_name }}
          
  cleanup-branch:
    if: github.event_name == 'delete' && github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: gh-pages
          
      - name: Remove branch directory
        run: |
          rm -rf ${{ github.event.ref }}
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Remove ${{ github.event.ref }} branch deployment" || exit 0
          git push
