name: Build Manuscript + Deploy Site

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install pandoc + TeX
      - name: Install pandoc
        uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: '3.1.11'
      - name: Install TeX Live (full)
        run: sudo apt-get update && sudo apt-get install -y texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra

      # Use our comprehensive make script
      - name: Build All Assets (TEX, PDF, HTML)
        run: ./make

      # Build Jekyll site
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: .
          destination: ./_site

      # Upload Pages artifact (so Pages can deploy it)
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

      # Keep outputs as artifacts too
      - name: Upload manuscript artifacts
        uses: actions/upload-artifact@v4
        with:
          name: manuscript
          path: |
            build/out/manuscript.pdf
            build/out/manuscript.tex
            assets/paper/manuscript.html
            assets/letters/*.html

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  release:
    if: github.event_name == 'release'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download built manuscript
        uses: actions/download-artifact@v4
        with:
          name: manuscript
          path: dist
      - name: Attach files to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.pdf
            dist/manuscript.tex
